In [27]:
import numpy as np
import scipy

Введем данные:

In [28]:
A = np.array([[1, 1], [2, -1], [1,3 ], [3, 1]],dtype=np.float64)
b = np.array([3, 0.2, 7, 5])

Видно, что столбцы $A$ -- линейно независимы. Следовательно, $x = (A^TA)^{-1}A^Tb$ -- решение. Посчитаем сначала $A^TA$.

In [29]:
diag = A.T @ A
diag

array([[15.,  5.],
       [ 5., 12.]])

Инвертируем ее:

In [30]:
inverse = np.linalg.inv(diag)
inverse

array([[ 0.07741935, -0.03225806],
       [-0.03225806,  0.09677419]])

Посчитаем ответ:

In [31]:
x = inverse @ A.T @ b
x

array([1.03741935, 1.96774194])

Сравним со встроенной функцией решения:

In [32]:
np.linalg.norm(x - np.linalg.lstsq(A, b)[0])

/tmp/ipykernel_461745/2875946979.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.norm(x - np.linalg.lstsq(A, b)[0])


6.280369834735101e-16

In [37]:
A = np.array([[1, 0, 1], [2, 3, 1], [0, 5, 1]])
np.linalg.eig(A.T @ A)

(array([37.27013192,  4.33361895,  0.39624913]),
 array([[-0.19894321, -0.89363827, -0.40228379],
        [-0.95035444,  0.27613894, -0.14343547],
        [-0.23926564, -0.35377668,  0.90420906]]))

In [34]:
A @ A.T

array([[ 2,  3,  1],
       [ 3, 14, 16],
       [ 1, 16, 26]])

In [35]:
scipy.linalg.svd(np.array([[1, 0, 1], [2, 3, 1], [0, 5, 1]]))

(array([[-0.07177954,  0.59921901,  0.79736082],
        [-0.57137709,  0.63054934, -0.52529586],
        [-0.81754261, -0.4932992 ,  0.29711947]]),
 array([6.10492686, 2.0817346 , 0.62948323]),
 array([[-0.19894321, -0.95035444, -0.23926564],
        [ 0.89363827, -0.27613894,  0.35377668],
        [-0.40228379, -0.14343547,  0.90420906]]))

In [36]:
np.sqrt(0.39)

0.6244997998398398

In [12]:
A = np.array([[3, 9.1, 2.1], [1.5, 3.5, 7], [5.4, 1.8, 5.3]])
np.linalg.cond(A)

4.141961386064743

In [13]:
np.linalg.norm(np.array([4.1, 1.7, 3.1]))

5.413871073455666

In [14]:
np.sqrt(3) / 5.4

0.32075014954979203